<?php
/**
 * Created by PhpStorm.
 * User: liyi
 * Date: 2018/4/25
 * Time: 上午9:47
 */

namespace common\widgets\nav;

use yii\web\AssetBundle;

class NavWidgetAsset extends AssetBundle
{
    public $js = [
        'js/navwidget.js',
    ];

    public $css = [
        'css/navwidget.css',
    ];

    public $depends = [
        "yii\web\JqueryAsset",
    ];

    public function init()
    {
        $this->sourcePath = __DIR__.'/assets';
        parent::init(); // TODO: Change the autogenerated stub
    }


}