<?php
/**
 * Created by PhpStorm.
 * User: liyi
 * Date: 2018/4/25
 * Time: 上午9:44
 */

namespace common\widgets\nav;

use yii\base\Widget;
use yii\helpers\Html;

class NavWidget extends Widget
{
    public $deep;
    public $categoryList;
    public $categoryCurrentId;
    public $topNavClass;
    public $topNavId;
    public $hasChildItemClass;  // li
    public $hasChildLinkClass;  // a
    public $hasChildLinkOption;  // a
    public $childNavClass;   // ul
    public $dropdownInsertDom;   // ul



    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        NavWidgetAsset::register($this->getView());
        return $this->render('_nav', [
            'deep' => $this->deep,
            'categoryList' => $this->categoryList,
            'categoryCurrentId' => $this->categoryCurrentId,
            'topNavClass' => $this->topNavClass,
            'topNavId' => $this->topNavId,
            'hasChildItemClass' => $this->hasChildItemClass,
            'hasChildLinkClass' => $this->hasChildLinkClass,
            'hasChildLinkOption' => $this->hasChildLinkOption,
            'childNavClass' => $this->childNavClass,
            'dropdownInsertDom' => $this->dropdownInsertDom,
        ]);
    }

    public function getViewPath()
    {
        return __DIR__.'/views/';
    }
}